---
- name: copy sch-executor run file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ app_user }}'
    group: '{{ app_group }}'
    mode: 0755
  notify: restart sch-executor
  when:
  with_items:
    - { src: 'sv-sch-executor-run.j2', dest: '{{ runit_sv_dir }}/sch-executor/run' }

- name: runit sv dir to service dir
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ app_user }}'
    group: '{{ app_group }}'
    state: link
  with_items:
    - { src: '{{ runit_sv_dir }}/sch-executor', dest: '{{ runit_service_dir }}/sch-executor' }

- name: dramatiq started
  runit:
    name=sch-executor
    state=started
    enabled=yes
    service_dir='{{ runit_service_dir }}'