---
dc_whl: 'fx-dc-{{ versions.app }}.zip'
dc_conf: 'fx-dc-{{ versions.app }}-config.zip'
dc_home_dir: '{{ lib_dir }}/dc'
dc_log_dir: '{{ log_dir }}/dc'
dc_conf_dir: '{{ conf_dir }}/dc'
dc_certs_dir: '{{ dc_conf_dir }}/certs/'
dc_data_dir: '{{ data_dir }}/dc'
py_rpm_filename_centos6: 'python-{{ versions.python2_centos6 }}'
py_rpm_filename_centos7: 'python-{{ versions.python2_centos7 }}'
tcl6_rpm_filename: 'tcl-{{ versions.tcl6 }}'
tcl7_rpm_filename: 'tcl-{{ versions.tcl7 }}'
wmic_rpm_filename: 'wmic-{{ versions.wmic }}'
telnet_rpm_filename: 'telnet-{{ versions.telnet }}'
navicli_rpm_filename: 'NaviCLI-Linux-{{ versions.navicli }}'
nmap_rpm_filename: 'nmap-{{ versions.nmap }}'
expect_rpm_filename: 'expect-{{ versions.expect }}'
