---
- hosts: mon
  roles: 
    - role: elasticsearch
    - role: kibana
    - role: heartbeat
    - role: nginx_app_config
    - role: app
    
  vars:
    - es_data_node: 'true'
    - es_ingest_node: 'true'
    - es_watcher_enable: 'false'
    - es_watcher_email_enable: 'false'
    - ansible_become: yes
    - ansible_become_user: 'root'
    - ansible_become_method: su